services:
  lms:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_B2_CDN_URL: ${NEXT_PUBLIC_B2_CDN_URL:-}
    container_name: lms
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      POCKETBASE_URL: ${POCKETBASE_URL}
